name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.401
    - name: Restore workloads
      run: dotnet workload restore
    - name: Restore dependencies
      run: dotnet restore Praeclarum.Utilities.sln
    - name: Build
      run: dotnet build --no-restore -c Release Praeclarum.Utilities.sln
    - name: Pack
      run: dotnet pack -c Release Praeclarum.Utilities.sln
